Laravel 8 and Backpack 5.x Upgrade
abhayagiri/abhayagiri-website pull request #262
Opened 2023-06-15 15:07 UTC by fsmonter

2023-06-15 15:10 UTC, fsmonter commented on .gitignore
> +auth.json
Every environment has to add an `auth.json` entry to authenticate the backpack/pro package.

2023-06-15 15:11 UTC, fsmonter commented
Hey @adammparker, upgrade tested on staging and is ready for production. Let me know what you think!

2023-06-15 20:11 UTC, adammparker requested changes
Only one code-level change I think, I poked around a little bit on staging and things look pretty much the same as before. Did you test some of the admin functionality like actually performing create/edit etc. functions?

2023-06-16 14:51 UTC, fsmonter commented on config/backpack/base.php
> +    'password_recovery_throttle_access' => '3,10',
Woops yes missed that. It's updated.

2023-06-16 17:20 UTC, adammparker approved these changes

2023-06-23 10:35 UTC, merged